version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
  reviewers:
  - danmurf
  ignore:
  - dependency-name: tzinfo
    versions:
    - ">= 2.0.a"
    - "< 2.1"
